'use client';

import { useMemo, useState } from 'react';
import { Archive, ChevronDown, ImagePlus, MoreHorizontal, Plus, Search, SlidersHorizontal, X } from 'lucide-react';
import { products } from '@/data/store';

export default function ProductsAdminPage() {
  const [query,setQuery]=useState(''); const [editorOpen,setEditorOpen]=useState(false);
  const visible=useMemo(()=>products.filter((product)=>`${product.name} ${product.category}`.toLowerCase().includes(query.toLowerCase())),[query]);
  return <><div className="admin-page-heading"><div><span className="admin-kicker">Catalog</span><h1>Products</h1><p>Shape the collection, variants, media and inventory.</p></div><div><button className="admin-button admin-button--secondary"><Archive size={15}/> Import</button><button onClick={()=>setEditorOpen(true)} className="admin-button admin-button--primary"><Plus size={15}/> Add product</button></div></div>
    <section className="inventory-stats"><div className="admin-card"><span>Active products</span><strong>84</strong><small>+6 this month</small></div><div className="admin-card"><span>Low stock</span><strong className="warning-text">7</strong><small>Needs attention</small></div><div className="admin-card"><span>Inventory value</span><strong>$28.4k</strong><small>At retail price</small></div><div className="admin-card"><span>Out of stock</span><strong className="danger-text">3</strong><small>2 with waitlists</small></div></section>
    <div className="admin-card table-card"><div className="table-toolbar"><label className="table-search"><Search size={16}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search products"/></label><button className="filter-pill"><SlidersHorizontal size={14}/> Collection <ChevronDown size={14}/></button><button className="filter-pill">Status <ChevronDown size={14}/></button></div><div className="admin-table admin-table--large"><table><thead><tr><th><input type="checkbox" aria-label="Select all products"/></th><th>Product</th><th>Status</th><th>Inventory</th><th>Category</th><th>Price</th><th>Updated</th><th></th></tr></thead><tbody>{visible.map((product)=><tr key={product.id}><td><input type="checkbox" aria-label={`Select ${product.name}`}/></td><td><div className="product-cell"><img src={product.image} alt=""/><section><strong>{product.name}</strong><small>MT-{String(product.id).padStart(4,'0')} · {product.colors.length} variants</small></section></div></td><td><span className={`status ${product.stock?'status--active':'status--cancelled'}`}>{product.stock?'Active':'Sold out'}</span></td><td><div className="stock-cell"><strong className={product.stock<8?'warning-text':''}>{product.stock}</strong><span><i style={{width:`${Math.min(product.stock*3,100)}%`}}/></span></div></td><td>{product.category}</td><td>${product.price.amount}</td><td>Today</td><td><button className="table-more"><MoreHorizontal size={17}/></button></td></tr>)}</tbody></table></div></div>
    {editorOpen&&<div className="panel-root"><button className="panel-scrim" onClick={()=>setEditorOpen(false)} aria-label="Close editor"/><aside className="editor-panel glass-overlay" role="dialog" aria-modal="true" aria-labelledby="editor-title"><header><div><span className="admin-kicker">New catalog piece</span><h2 id="editor-title">Add product</h2></div><button className="icon-button" onClick={()=>setEditorOpen(false)}><X/></button></header><div className="editor-body"><section className="editor-section"><h3>Story</h3><label>Title<input placeholder="e.g. Galata Silk Pendant"/></label><label>Description<textarea rows={5} placeholder="Tell the story of this piece…"/></label></section><section className="editor-section"><h3>Media</h3><button className="upload-zone"><ImagePlus/><strong>Drop photography here</strong><span>JPEG, PNG or WebP · up to 10 MB</span></button></section><section className="editor-section"><h3>Pricing</h3><div className="editor-grid"><label>Price<input type="number" placeholder="0.00"/></label><label>Compare-at price<input type="number" placeholder="0.00"/></label></div></section><section className="editor-section"><h3>Variants</h3><div className="variant-row"><span>Finish</span><strong>Gold · Silver · Rose</strong><button>Edit</button></div><button className="add-option"><Plus size={14}/> Add option</button></section><section className="editor-section"><h3>Search preview</h3><label>Page title<input placeholder="Product title · MERS Tassel"/></label><label>Meta description<textarea rows={3}/></label></section></div><footer><button className="admin-button admin-button--secondary" onClick={()=>setEditorOpen(false)}>Save draft</button><button className="admin-button admin-button--primary" onClick={()=>setEditorOpen(false)}>Publish product</button></footer></aside></div>}
  </>;
}
