using MersTassel.Application.Common;
using MersTassel.Application.DTOs;
using MersTassel.Application.Interfaces;
using MersTassel.Domain.Entities;
using MersTassel.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace MersTassel.Infrastructure.Services;

public class BlogService(AppDbContext db) : IBlogService
{
    static BlogPostSummaryDto Summary(BlogPost p) => new(p.Id,p.Title,p.TitleTr,p.Slug,p.Excerpt,p.ExcerptTr,p.CoverImagePath,p.Category,p.Tags,p.ReadingTimeMinutes,p.PublishedAt,p.Comments.Count(c=>c.Status==BlogCommentStatus.Approved));
    static BlogCommentDto Comment(BlogComment c) => new(c.Id,c.PostId,c.Post.Title,c.AuthorName,c.Content,c.Status,c.CreatedAt);
    static BlogPostDetailDto Detail(BlogPost p, bool admin=false) => new(p.Id,p.Title,p.TitleTr,p.Slug,p.Excerpt,p.ExcerptTr,p.Content,p.ContentTr,p.CoverImagePath,p.AuthorName,p.AuthorAvatarPath,p.Category,p.Tags,p.ReadingTimeMinutes,p.IsPublished,p.PublishedAt,p.Comments.Where(c=>admin || c.Status==BlogCommentStatus.Approved).OrderByDescending(c=>c.CreatedAt).Select(Comment).ToList());

    public async Task<PagedResult<BlogPostSummaryDto>> GetPublishedPostsAsync(string? tag,string? search,int page,int pageSize,CancellationToken ct=default) { page=Math.Max(1,page); pageSize=Math.Clamp(pageSize,1,50); var q=db.BlogPosts.AsNoTracking().Include(x=>x.Comments).Where(x=>x.IsPublished&&x.PublishedAt<=DateTimeOffset.UtcNow); if(!string.IsNullOrWhiteSpace(tag)) q=q.Where(x=>x.Category==tag || (x.Tags!=null&&x.Tags.Contains(tag))); if(!string.IsNullOrWhiteSpace(search)) q=q.Where(x=>x.Title.Contains(search)||x.Excerpt.Contains(search)||(x.TitleTr!=null&&x.TitleTr.Contains(search))); var total=await q.CountAsync(ct); var items=(await q.OrderByDescending(x=>x.PublishedAt).Skip((page-1)*pageSize).Take(pageSize).ToListAsync(ct)).Select(Summary).ToList(); return new(items,page,pageSize,total); }
    public async Task<IReadOnlyList<BlogPostSummaryDto>> GetFeaturedPostsAsync(int count,CancellationToken ct=default) => (await db.BlogPosts.AsNoTracking().Include(x=>x.Comments).Where(x=>x.IsPublished&&x.PublishedAt<=DateTimeOffset.UtcNow).OrderByDescending(x=>x.PublishedAt).Take(Math.Clamp(count,1,12)).ToListAsync(ct)).Select(Summary).ToList();
    public async Task<BlogPostDetailDto> GetPostBySlugAsync(string slug,CancellationToken ct=default) { var p=await db.BlogPosts.AsNoTracking().Include(x=>x.Comments).FirstOrDefaultAsync(x=>x.Slug==slug&&x.IsPublished&&x.PublishedAt<=DateTimeOffset.UtcNow,ct) ?? throw new NotFoundException("Journal story not found."); return Detail(p); }
    public async Task<BlogCommentDto> AddCommentAsync(string slug,CreateBlogCommentDto dto,string? customerId,CancellationToken ct=default) { var p=await db.BlogPosts.FirstOrDefaultAsync(x=>x.Slug==slug&&x.IsPublished,ct) ?? throw new NotFoundException("Journal story not found."); var c=new BlogComment{Post=p,AuthorName=dto.AuthorName.Trim(),AuthorEmail=dto.AuthorEmail.Trim().ToLowerInvariant(),Content=dto.Content.Trim(),CustomerId=customerId,Status=BlogCommentStatus.Pending}; db.BlogComments.Add(c); await db.SaveChangesAsync(ct); return Comment(c); }
    public async Task<IReadOnlyList<BlogPostDetailDto>> GetAdminPostsAsync(CancellationToken ct=default) => (await db.BlogPosts.Include(x=>x.Comments).OrderByDescending(x=>x.PublishedAt).ToListAsync(ct)).Select(x=>Detail(x,true)).ToList();
    public async Task<BlogPostDetailDto> GetPostByIdAsync(int id,CancellationToken ct=default) { var p=await db.BlogPosts.Include(x=>x.Comments).FirstOrDefaultAsync(x=>x.Id==id,ct)??throw new NotFoundException("Story not found."); return Detail(p,true); }
    public async Task<BlogPostDetailDto> CreatePostAsync(CreateBlogPostDto d,CancellationToken ct=default) { if(await db.BlogPosts.AnyAsync(x=>x.Slug==d.Slug,ct)) throw new ConflictException("Slug is already in use."); var p=new BlogPost{Title=d.Title,TitleTr=d.TitleTr,Slug=d.Slug,Excerpt=d.Excerpt,ExcerptTr=d.ExcerptTr,Content=d.Content,ContentTr=d.ContentTr,CoverImagePath=d.CoverImagePath,AuthorName=string.IsNullOrWhiteSpace(d.AuthorName)?"MERS Atelier":d.AuthorName,AuthorAvatarPath=d.AuthorAvatarPath,Category=d.Category,Tags=d.Tags,ReadingTimeMinutes=d.ReadingTimeMinutes,IsPublished=d.IsPublished,PublishedAt=d.PublishedAt??DateTimeOffset.UtcNow}; db.Add(p); await db.SaveChangesAsync(ct); return Detail(p,true); }
    public async Task<BlogPostDetailDto> UpdatePostAsync(int id,UpdateBlogPostDto d,CancellationToken ct=default) { var p=await db.BlogPosts.Include(x=>x.Comments).FirstOrDefaultAsync(x=>x.Id==id,ct)??throw new NotFoundException("Story not found."); if(await db.BlogPosts.AnyAsync(x=>x.Id!=id&&x.Slug==d.Slug,ct)) throw new ConflictException("Slug is already in use."); p.Title=d.Title;p.TitleTr=d.TitleTr;p.Slug=d.Slug;p.Excerpt=d.Excerpt;p.ExcerptTr=d.ExcerptTr;p.Content=d.Content;p.ContentTr=d.ContentTr;p.CoverImagePath=d.CoverImagePath;p.AuthorName=d.AuthorName;p.AuthorAvatarPath=d.AuthorAvatarPath;p.Category=d.Category;p.Tags=d.Tags;p.ReadingTimeMinutes=d.ReadingTimeMinutes;p.IsPublished=d.IsPublished;p.PublishedAt=d.PublishedAt; await db.SaveChangesAsync(ct); return Detail(p,true); }
    public async Task DeletePostAsync(int id,CancellationToken ct=default) { var p=await db.BlogPosts.FindAsync([id],ct)??throw new NotFoundException("Story not found."); p.IsDelete=true;p.DeletedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(ct); }
    public async Task<IReadOnlyList<BlogCommentDto>> GetAdminCommentsAsync(BlogCommentStatus? status,CancellationToken ct=default) { var q=db.BlogComments.AsNoTracking().Include(x=>x.Post).AsQueryable();if(status.HasValue)q=q.Where(x=>x.Status==status);return (await q.OrderByDescending(x=>x.CreatedAt).ToListAsync(ct)).Select(Comment).ToList(); }
    public async Task<BlogCommentDto> ModerateCommentAsync(int id,BlogCommentStatus status,CancellationToken ct=default) { var c=await db.BlogComments.Include(x=>x.Post).FirstOrDefaultAsync(x=>x.Id==id,ct)??throw new NotFoundException("Comment not found.");c.Status=status;await db.SaveChangesAsync(ct);return Comment(c); }
    public async Task DeleteCommentAsync(int id,CancellationToken ct=default) { var c=await db.BlogComments.FindAsync([id],ct)??throw new NotFoundException("Comment not found.");db.Remove(c);await db.SaveChangesAsync(ct); }
}
