# Generated by Django 6.0.6 on 2026-08-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("page", models.CharField(default="/", max_length=200)),
                ("referrer", models.URLField(blank=True, null=True)),
                ("visited_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-visited_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitorCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_visits", models.PositiveIntegerField(default=0)),
                ("unique_visitors", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Visitor Count",
                "verbose_name_plural": "Visitor Count",
            },
        ),
    ]
