# Generated by Django 6.0.6 on 2026-08-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommerceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=64)),
                ("session_id", models.CharField(db_index=True, max_length=72)),
                (
                    "user_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "order_number",
                    models.CharField(blank=True, db_index=True, max_length=24),
                ),
                ("source", models.CharField(blank=True, max_length=80)),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("orders", models.PositiveIntegerField(default=0)),
                ("sessions", models.PositiveIntegerField(default=0)),
                ("conversions", models.PositiveIntegerField(default=0)),
                (
                    "ad_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
