# Generated by Django 6.0.6 on 2026-08-15 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_existing_profiles(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    UserProfile = apps.get_model('accounts', 'UserProfile')
    used_emails = set()
    for user in User.objects.using(schema_editor.connection.alias).all().order_by('id'):
        email = (user.email or f'user-{user.pk}@invalid.local').strip().lower()
        if email in used_emails:
            email = f'user-{user.pk}@invalid.local'
        used_emails.add(email)
        role = 'admin' if user.is_superuser else 'staff' if user.is_staff else 'customer'
        UserProfile.objects.using(schema_editor.connection.alias).create(user_id=user.pk, email=email, role=role)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("staff", "Staff"),
                            ("admin", "Administrator"),
                        ],
                        default="customer",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_existing_profiles, migrations.RunPython.noop),
    ]
