# Generated by Django 6.0.6 on 2026-08-15 16:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def prepare_user_owned_open_carts(apps, schema_editor):
    Cart = apps.get_model('commerce', 'Cart')
    carts = Cart.objects.using(schema_editor.connection.alias)
    carts.filter(status='open', user__isnull=True).update(status='abandoned')
    user_ids = carts.filter(status='open', user__isnull=False).values_list('user_id', flat=True).distinct()
    for user_id in user_ids:
        open_ids = list(carts.filter(user_id=user_id, status='open').order_by('-updated_at', '-created_at').values_list('id', flat=True))
        if len(open_ids) > 1:
            carts.filter(id__in=open_ids[1:]).update(status='abandoned')


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0002_stripeevent_order_paid_at_order_payment_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="added_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(prepare_user_owned_open_carts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False),
                    models.Q(("status", "open"), _negated=True),
                    _connector="OR",
                ),
                name="open_cart_requires_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("user",),
                name="unique_open_cart_per_user",
            ),
        ),
    ]
