'use client';

import { useMemo, useState } from 'react';
import { Clock3, Filter, Grid2X2, List, MessageSquareText, MoreHorizontal, Paperclip, Search, Send, ShoppingBag, Smile, Sparkles, UserRound, X } from 'lucide-react';
import { tickets as initialTickets } from '@/data/store';
import { Ticket } from '@/types/commerce';

export default function SupportPage(){const [tickets,setTickets]=useState(initialTickets);const [selectedId,setSelectedId]=useState(initialTickets[0].id);const [query,setQuery]=useState('');const [note,setNote]=useState(false);const [message,setMessage]=useState('');const [view,setView]=useState<'inbox'|'board'>('inbox');const selected=tickets.find((ticket)=>ticket.id===selectedId)!;const visible=useMemo(()=>tickets.filter((ticket)=>`${ticket.subject} ${ticket.customer}`.toLowerCase().includes(query.toLowerCase())),[tickets,query]);
const send=()=>{if(!message.trim())return;setTickets((current)=>current.map((ticket)=>ticket.id===selectedId?{...ticket,messages:[...ticket.messages,{id:Date.now(),from:'staff',body:message,time:'Now',internal:note}],status:'In progress'}:ticket));setMessage('')};
return <><div className="admin-page-heading support-heading"><div><span className="admin-kicker">Customer care</span><h1>Support</h1><p>Warm, contextual care—with every order close at hand.</p></div><div className="view-switch"><button className={view==='inbox'?'active':''} onClick={()=>setView('inbox')}><List size={15}/> Inbox</button><button className={view==='board'?'active':''} onClick={()=>setView('board')}><Grid2X2 size={15}/> Board</button></div></div>
{view==='board'?<div className="ticket-board">{(['Open','In progress','Resolved'] as const).map((status)=><section key={status}><header><span>{status}</span><b>{tickets.filter((ticket)=>ticket.status===status).length}</b></header>{tickets.filter((ticket)=>ticket.status===status).map((ticket)=><button key={ticket.id} onClick={()=>{setSelectedId(ticket.id);setView('inbox')}}><div><span className={`priority priority--${ticket.priority.toLowerCase().replace(' ','-')}`}>{ticket.priority}</span><small>{ticket.id}</small></div><h3>{ticket.subject}</h3><p>{ticket.customer}</p><footer><span><MessageSquareText size={13}/>{ticket.messages.length}</span><span><Clock3 size={13}/>{ticket.sla}</span></footer></button>)}</section>)}</div>:<div className="support-workspace admin-card"><aside className="ticket-list"><div className="ticket-list__toolbar"><label><Search size={15}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search conversations"/></label><button><Filter size={15}/></button></div><div className="ticket-list__filters"><button className="active">All <b>{tickets.length}</b></button><button>Mine</button><button>Unassigned</button></div><div className="ticket-scroll">{visible.map((ticket)=><button key={ticket.id} className={ticket.id===selectedId?'active':''} onClick={()=>setSelectedId(ticket.id)}><div><span className={`priority-dot priority-dot--${ticket.priority.toLowerCase().replace(' ','-')}`}/><strong>{ticket.customer}</strong><small>{ticket.updated}</small></div><h3>{ticket.subject}</h3><p>{ticket.messages.at(-1)?.body}</p><footer><span className={`status status--${ticket.status.toLowerCase().replace(' ','-')}`}>{ticket.status}</span><span><Clock3 size={11}/>{ticket.sla}</span></footer></button>)}</div></aside>
<section className="thread-panel"><header className="thread-header"><div><span className={`priority priority--${selected.priority.toLowerCase().replace(' ','-')}`}>{selected.priority}</span><h2>{selected.subject}</h2><p>{selected.id} · Started today via email</p></div><div><select value={selected.status} onChange={(event)=>setTickets((current)=>current.map((ticket)=>ticket.id===selected.id?{...ticket,status:event.target.value as Ticket['status']}:ticket))}><option>Open</option><option>In progress</option><option>Resolved</option></select><button><MoreHorizontal/></button></div></header><div className="thread-scroll"><div className="thread-day">Today</div>{selected.messages.map((item)=><article key={item.id} className={`message message--${item.from}${item.internal?' message--internal':''}`}><span>{item.from==='customer'?selected.customer.split(' ').map((n)=>n[0]).join(''):'DS'}</span><div>{item.internal&&<small>Internal note · only your team can see this</small>}<p>{item.body}</p><time>{item.time}</time></div></article>)}</div><div className={`reply-box${note?' reply-box--note':''}`}><div className="reply-tabs"><button className={!note?'active':''} onClick={()=>setNote(false)}>Reply</button><button className={note?'active':''} onClick={()=>setNote(true)}>Internal note</button></div><textarea value={message} onChange={(event)=>setMessage(event.target.value)} placeholder={note?'Write a private note for your team…':'Write a thoughtful reply…'} onKeyDown={(event)=>{if(event.key==='Enter'&&(event.metaKey||event.ctrlKey))send()}}/><footer><div><button aria-label="Attach file"><Paperclip/></button><button aria-label="Insert emoji"><Smile/></button><button><Sparkles/> Canned response</button></div><button onClick={send}><Send size={14}/>{note?'Add note':'Send reply'}</button></footer></div></section>
<aside className="customer-context"><header><span>{selected.customer.split(' ').map((n)=>n[0]).join('')}</span><h3>{selected.customer}</h3><p>{selected.email}</p></header><div className="context-metrics"><div><strong>${selected.spend}</strong><span>Lifetime spend</span></div><div><strong>4</strong><span>Total orders</span></div></div><section><h4>Active order</h4><div className="context-order"><ShoppingBag/><span><strong>{selected.orderId||'No active order'}</strong><small>Processing · 2 pieces</small></span></div><button>View full order ↗</button></section><section><h4>Customer details</h4><p><span>Location</span><strong>Istanbul, Türkiye</strong></p><p><span>Customer since</span><strong>June 2024</strong></p><p><span>Preferred language</span><strong>English</strong></p></section><section><h4>Tags</h4><div className="tag-list"><span>Collector</span><span>High value</span><button>+</button></div></section></aside></div>}</>}
