'use client';

import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Locale = 'en' | 'tr';

const en = {
  'language.label': 'Language', 'language.en': 'English', 'language.tr': 'Turkish',
  'nav.home': 'Home', 'nav.shop': 'Shop', 'nav.story': 'Our story', 'nav.journal': 'Contact', 'nav.admin': 'Atelier admin',
  'header.menu': 'Toggle navigation', 'header.search': 'Search', 'header.searchPlaceholder': 'Search rings, bags, keychains…', 'header.submitSearch': 'View results', 'header.closeSearch': 'Close search', 'header.saved': 'Saved pieces', 'header.account': 'Your account', 'header.bag': 'Open bag with {{count}} items', 'header.light': 'Use light theme', 'header.dark': 'Use dark theme', 'header.home': 'MERS Tassel home', 'header.navigation': 'Main navigation',
  'common.explore': 'Explore the collection', 'common.continueShopping': 'Continue shopping', 'common.loading': 'Curating the collection…', 'common.loadingShort': 'Loading…', 'common.previous': 'Previous', 'common.next': 'Next', 'common.retry': 'Try again', 'common.errorTitle': 'Something went wrong', 'common.offlineTitle': 'Cannot reach the service', 'common.offlineCopy': 'The atelier service is not responding. Please try again in a moment.', 'common.unexpected': 'An unexpected error occurred.', 'common.atelierAlt': 'MERS Tassel atelier', 'common.jewelryAlt': 'Handcrafted jewelry detail', 'common.studioDetailAlt': 'Details from the MERS Tassel studio',
  'footer.tagline': 'Small objects of beauty, shaped by hand in Türkiye and designed to stay with you.', 'footer.explore': 'Explore', 'footer.shopAll': 'Shop all', 'footer.new': 'New arrivals', 'footer.atelier': 'Our atelier', 'footer.care': 'Customer care', 'footer.contact': 'Contact', 'footer.shipping': 'Shipping & delivery', 'footer.returns': 'Returns & withdrawal', 'footer.jewelryCare': 'Jewelry care', 'footer.privacy': 'Privacy & security', 'footer.security': 'Privacy & security', 'footer.invest': 'Invest in MERS', 'footer.notes': 'Atelier notes', 'footer.notesCopy': 'New pieces, quiet stories, once or twice a month.', 'footer.email': 'Email address', 'footer.subscribe': 'Subscribe', 'footer.follow': 'Follow & say hello',
  'home.eyebrow': 'Istanbul · Est. 2018', 'home.title1': 'Wear a little', 'home.title2': 'wonder.', 'home.lede': 'Jewelry with a sense of place—hand-finished in our Istanbul atelier, made to gather stories as beautifully as it gathers light.', 'home.makers': 'Meet the makers', 'home.proof': 'Loved by 2,400+ collectors', 'home.pick': 'Atelier pick', 'home.handknotted': 'Hand-finished in the atelier', 'home.viewProduct': 'View this piece', 'home.scroll': 'Scroll to discover',
  'home.handmade': 'Made by hand', 'home.handmadeSub': 'In our Istanbul atelier', 'home.materials': 'Considered materials', 'home.materialsSub': 'Selected for beauty & longevity', 'home.gift': 'Gift-ready always', 'home.giftSub': 'Wrapped with a handwritten note',
  'home.signature': 'The signature edit', 'home.keepClose': 'Pieces to keep close.', 'home.shopAll': 'Shop all pieces', 'home.ritual': 'Find your ritual', 'home.everyday1': 'Made for every day,', 'home.everyday2': 'and the days you remember.', 'home.pieces': '{{count}} pieces',
  'home.hands': 'Hands before machines', 'home.slowTitle': 'Nothing meaningful is made in a hurry.', 'home.slowCopy': 'Every MERS piece passes between the hands of our small team—from sketch to stone selection, knotting, polishing and the final, quiet inspection.', 'home.quote': '“We make each object as if it were already someone’s keepsake.”', 'home.quoteBy': '— Meral S., founder & maker', 'home.stepInside': 'Step inside the atelier', 'home.atelierCaption': 'The atelier · Karaköy, Istanbul',
  'home.review': 'Even lovelier in person. It feels thoughtful from the first touch—the weight, the tiny details, even the box.', 'home.verified': 'Verified collector · Istanbul', 'home.letters': 'Letters from the atelier', 'home.inbox': 'A slower kind of inbox.', 'home.inboxCopy': 'New objects, studio notes and Istanbul details. Sent sparingly.', 'home.join': 'Join the list', 'home.privacy': 'By subscribing, you agree to our privacy terms.',
  'catalog.eyebrow': 'The collection', 'catalog.title1': 'Objects for', 'catalog.title2': 'everyday wonder.', 'catalog.lede': 'Made slowly in Istanbul. Designed to feel unmistakably yours.', 'catalog.categories': 'Product categories', 'catalog.all': 'All pieces', 'catalog.filters': 'Filters', 'catalog.sort': 'Sort products', 'catalog.featured': 'Featured', 'catalog.newest': 'Newest', 'catalog.low': 'Price: low to high', 'catalog.high': 'Price: high to low', 'catalog.search': 'Search the collection', 'catalog.searchPlaceholder': 'Try “pearl” or “ring”', 'catalog.clearSearch': 'Clear search', 'catalog.availability': 'Availability', 'catalog.allAvailability': 'All availability', 'catalog.ready': 'Ready to ship', 'catalog.made': 'Made to order', 'catalog.material': 'Material', 'catalog.allMaterials': 'All materials', 'catalog.gold': 'Gold vermeil', 'catalog.silver': 'Sterling silver', 'catalog.silk': 'Silk', 'catalog.count': '{{count}} considered pieces', 'catalog.clear': 'Clear filters', 'catalog.empty': 'No pieces found.', 'catalog.emptyCopy': 'Try a broader search or clear your filters.', 'catalog.viewAll': 'View all pieces', 'catalog.promise': 'The MERS promise', 'catalog.promiseTitle': 'Made in small editions. Never mass produced.', 'catalog.promiseCopy': 'Our hands set the pace. When a piece is gone, it may take a little while to return—and sometimes that is part of its beauty.',
  'product.new': 'New', 'product.save': 'Save ${{amount}}', 'product.soldOut': 'Sold out', 'product.savePiece': 'Save {{name}}', 'product.quickAdd': 'Quick add', 'product.unavailable': 'Unavailable', 'product.view': 'View {{name}}',
  'cart.eyebrow': 'Your selection', 'cart.title': 'Shopping bag', 'cart.close': 'Close', 'cart.emptyTitle': 'Your bag is beautifully empty.', 'cart.emptyCopy': 'Discover a piece made slowly, by hand.', 'cart.remove': 'Remove {{name}}', 'cart.quantity': 'Quantity for {{name}}', 'cart.decrease': 'Decrease quantity', 'cart.increase': 'Increase quantity', 'cart.subtotal': 'Subtotal', 'cart.delivery': 'Estimated delivery', 'cart.tax': 'Estimated tax', 'cart.total': 'Estimated total', 'cart.taxNote': 'Tax is an estimate and is finalized during secure checkout.', 'cart.complimentary': 'Complimentary', 'cart.checkout': 'Continue to checkout', 'cart.updateFailed': 'Bag not updated', 'cart.addFailed': 'This piece could not be added to your bag.', 'cart.removeFailed': 'This piece could not be removed.', 'cart.quantityFailed': 'The quantity could not be updated.',
  'pdp.collection': 'Collection', 'pdp.handmade': 'Made by hand', 'pdp.stories': '{{count}} stories', 'pdp.saveAmount': 'You save ${{amount}}', 'pdp.finish': 'Finish', 'pdp.choose': 'Choose {{option}}', 'pdp.add': 'Add to bag · ${{amount}}', 'pdp.waitlist': 'Join the waitlist', 'pdp.stock': 'Only {{count}} left in the atelier', 'pdp.delivery': 'Complimentary delivery', 'pdp.deliverySub': '500 TL+ orders delivered in Eskişehir', 'pdp.returns': 'Statutory withdrawal', 'pdp.returnsSub': 'Within 14 days', 'pdp.care': 'Atelier care', 'pdp.careSub': 'Ask us about repairs', 'pdp.story': 'Story & details', 'pdp.materials': 'Materials & dimensions', 'pdp.careGuide': 'Care guide', 'pdp.variation': 'Each piece is finished by hand, so subtle variations are part of its character.', 'pdp.careCopy': 'Keep dry and away from perfume. Wipe gently with the supplied soft cloth, then store in its pouch between wears.', 'pdp.exploreDetail': 'Hover to explore detail', 'pdp.related': 'Continue exploring', 'pdp.love': 'You may also love.',
  'checkout.secure': 'Secure Stripe checkout', 'checkout.back': 'Continue shopping', 'checkout.eyebrow': 'Almost yours', 'checkout.title': 'Checkout', 'checkout.contact': 'Contact', 'checkout.contactCopy': 'Your receipt and delivery updates will arrive here.', 'checkout.email': 'Email address', 'checkout.emailError': 'Enter a valid email address', 'checkout.delivery': 'Delivery', 'checkout.deliveryCopy': 'Choose your pace. Stripe securely collects the delivery address next.', 'checkout.standard': 'PTT standard', 'checkout.standardTime': '3–5 business days', 'checkout.express': 'Express', 'checkout.expressTime': '1–2 business days', 'checkout.payment': 'Secure payment', 'checkout.paymentCopy': 'You’ll finish on Stripe’s encrypted, PCI-compliant payment page.', 'checkout.methods': 'Cards & local payment methods', 'checkout.methodsCopy': 'Available methods adapt to your region and device.', 'checkout.neverStores': 'MERS Tassel never sees or stores your card number.', 'checkout.opening': 'Opening secure checkout…', 'checkout.continue': 'Continue to payment · ${{amount}}', 'checkout.legal': 'Prices and availability are verified by the atelier server before Stripe opens. Taxes, where applicable, are finalized on the secure payment page.', 'checkout.summary': 'Order summary', 'checkout.empty': 'Your bag is empty.', 'checkout.browse': 'Browse the collection', 'checkout.trust': 'Secure checkout · 14-day withdrawal · PTT delivery', 'checkout.emptyToast': 'Your bag is empty', 'checkout.emptyToastCopy': 'Choose a piece before continuing to payment.', 'checkout.failed': 'Checkout could not start', 'checkout.retry': 'Please try again in a moment.', 'checkout.orderPlaced': 'Your order is reserved', 'checkout.paymentsUnavailable': 'Online payment is not enabled on this deployment. Your order and stock are held — the atelier will be in touch to complete payment.',
  'success.reference': 'Secure confirmation', 'success.confirming': 'Confirming your piece…', 'success.confirmingCopy': 'Stripe has returned you safely. We’re waiting for the signed payment confirmation—this usually takes only a moment.', 'success.paid': 'It’s yours.', 'success.paidCopy': 'Thank you. Your piece is now being prepared at the atelier, and the receipt is on its way to your inbox.', 'success.failed': 'Payment needs another try.', 'success.failedCopy': 'No charge was completed. Your bag remains ready whenever you would like to try again.', 'success.started': 'Atelier preparation started', 'success.payment': 'Payment {{status}}', 'success.pieces': '{{count}} pieces', 'success.piece': '{{count}} piece', 'success.tryAgain': 'Try payment again', 'success.missing': 'This confirmation link is missing its secure session reference.', 'success.retrieve': 'We could not retrieve this order yet.',
  'cancel.eyebrow': 'Checkout paused', 'cancel.title': 'Your bag is still here.', 'cancel.copy': 'No payment was completed and nothing in your persisted bag was removed. Return to checkout when the moment feels right.', 'cancel.return': 'Return to secure checkout', 'cancel.explore': 'Keep exploring',
  'about.eyebrow': 'Istanbul · Since 2018', 'about.title1': 'Made slowly.', 'about.title2': 'Kept for years.', 'about.lede': 'MERS began with a silk tassel, a shared workbench and a belief that everyday objects can carry uncommon feeling.', 'about.beginning': 'Our beginning', 'about.idea': 'A small idea, tied by hand.', 'about.p1': 'Founder Meral grew up among fabric merchants, metalsmiths and the crowded color of Istanbul. After years in fashion, she returned to the gestures she remembered most: knotting silk, polishing metal and choosing each stone by eye.', 'about.p2': 'What began at a kitchen table is now a close-knit atelier. We still work in small editions, still know who touched every piece, and still wrap each order as though it were a gift between friends.', 'about.quote': 'Beauty feels different when you can sense the person who made it.', 'about.guides': 'What guides us', 'about.care': 'Care, in every layer.', 'about.hands': 'Hands before machines', 'about.handsCopy': 'Human rhythm gives each piece its subtle, singular character.', 'about.memory': 'Materials with memory', 'about.memoryCopy': 'We choose materials that age beautifully and invite repair.', 'about.less': 'Less, but better', 'about.lessCopy': 'Small editions, considered packaging and no trend-chasing.', 'about.keepsake': 'Your next keepsake', 'about.find': 'Find the one that feels like you.',
  'contact.eyebrow': 'A note between us', 'contact.title1': 'We’d love to', 'contact.title2': 'hear from you.', 'contact.lede': 'Questions about a piece, an order, or a repair? Our small care team replies within one atelier day.', 'contact.write': 'Write', 'contact.visit': 'Visit', 'contact.appointment': 'By appointment', 'contact.connect': 'Stay connected', 'contact.connectCopy': 'Message us directly or follow the atelier.', 'contact.quote': '“A considered reply is part of the craft.”', 'contact.sent': 'Your note is with us.', 'contact.sentCopy': 'We’ll return to you within one atelier day.', 'contact.another': 'Send another', 'contact.name': 'Name', 'contact.email': 'Email', 'contact.help': 'What can we help with?', 'contact.product': 'A product question', 'contact.order': 'My order', 'contact.repairs': 'Repairs & care', 'contact.press': 'Press & partnerships', 'contact.message': 'Your message', 'contact.placeholder': 'Tell us a little more…', 'contact.send': 'Send your note',
  'social.instagram': 'Instagram', 'social.tiktok': 'TikTok', 'social.email': 'Email', 'social.whatsapp': 'WhatsApp',
  'auth.welcome': 'Welcome back', 'auth.await1': 'Your collection', 'auth.await2': 'awaits.', 'auth.loginCopy': 'Sign in to view orders, saved pieces and atelier care.', 'auth.password': 'Password', 'auth.showPassword': 'Show password', 'auth.remember': 'Remember me', 'auth.forgot': 'Forgot password?', 'auth.signIn': 'Sign in', 'auth.signingIn': 'Signing in…', 'auth.new': 'New to MERS?', 'auth.create': 'Create an account', 'auth.loginQuote': 'Objects of quiet beauty, made to stay with you.', 'auth.join': 'Join the atelier', 'auth.begin1': 'Begin your', 'auth.begin2': 'collection.', 'auth.signupCopy': 'Save favorites, track orders and receive private atelier notes.', 'auth.first': 'First name', 'auth.last': 'Last name', 'auth.consent': 'Send me occasional atelier notes and early collection access.', 'auth.createAccount': 'Create account', 'auth.creating': 'Creating account…', 'auth.already': 'Already a collector?', 'auth.signupQuote': 'A place for pieces with a story.', 'auth.loginError': 'We could not sign you in. Check your email and password.', 'auth.locked': 'Too many attempts. Please try again in a few minutes.', 'auth.signupError': 'We could not create your account. Please review your details.', 'auth.connectionError': 'The account service is offline. Restart the site with npm run dev, then try again.', 'auth.emailExists': 'An account already exists for this email. Try signing in instead.', 'auth.passwordRejected': 'Choose a password with at least eight characters, one letter and one number.', 'auth.firstError': 'Enter your first name.', 'auth.lastError': 'Enter your last name.', 'auth.emailError': 'Enter a valid email address.', 'auth.bagRequired': 'Sign in or create an account to use your shopping bag.', 'auth.signOut': 'Sign out',
  'account.eyebrow': 'Your MERS account', 'account.greeting': 'Welcome, {{name}}.', 'account.lede': 'Your collection, orders and atelier relationship in one considered place.', 'account.memberSince': 'Collector since', 'account.membership': 'Membership', 'account.collector': 'MERS collector', 'account.bagEyebrow': 'Saved across devices', 'account.bag': 'Your shopping bag', 'account.viewBag': 'View bag', 'account.quantity': 'Qty {{count}}', 'account.bagSummary': '{{count}} pieces in your bag', 'account.emptyBag': 'Your shopping bag is waiting for its first piece.', 'account.ordersEyebrow': 'Order history', 'account.orders': 'Your orders', 'account.loadingOrders': 'Gathering your orders…', 'account.ordersError': 'Your orders could not be loaded right now.', 'account.noOrders': 'No orders yet. Your first keepsake is still waiting to be found.', 'account.startShopping': 'Explore the collection', 'account.items': '{{count}} items', 'account.status.pending': 'Pending', 'account.status.processing': 'Processing', 'account.status.shipped': 'Shipped', 'account.status.delivered': 'Delivered', 'account.status.cancelled': 'Cancelled', 'account.status.refunded': 'Refunded', 'account.openAtelier': 'Open the atelier workspace',
} as const;

export type TranslationKey = keyof typeof en;

const tr: Record<TranslationKey, string> = {
  'language.label': 'Dil', 'language.en': 'İngilizce', 'language.tr': 'Türkçe',
  'nav.home': 'Ana sayfa', 'nav.shop': 'Mağaza', 'nav.story': 'Hikâyemiz', 'nav.journal': 'İletişim', 'nav.admin': 'Atölye yönetimi',
  'header.menu': 'Menüyü aç veya kapat', 'header.search': 'Ara', 'header.searchPlaceholder': 'Yüzük, çanta, anahtarlık ara…', 'header.submitSearch': 'Sonuçları gör', 'header.closeSearch': 'Aramayı kapat', 'header.saved': 'Kaydedilen parçalar', 'header.account': 'Hesabınız', 'header.bag': '{{count}} ürün bulunan çantayı aç', 'header.light': 'Açık temayı kullan', 'header.dark': 'Koyu temayı kullan', 'header.home': 'MERS Tassel ana sayfası', 'header.navigation': 'Ana menü',
  'common.explore': 'Koleksiyonu keşfet', 'common.continueShopping': 'Alışverişe devam et', 'common.loading': 'Koleksiyon hazırlanıyor…', 'common.loadingShort': 'Yükleniyor…', 'common.previous': 'Önceki', 'common.next': 'Sonraki', 'common.retry': 'Tekrar dene', 'common.errorTitle': 'Bir sorun oluştu', 'common.offlineTitle': 'Hizmete ulaşılamıyor', 'common.offlineCopy': 'Atölye hizmeti şu anda yanıt vermiyor. Lütfen biraz sonra tekrar deneyin.', 'common.unexpected': 'Beklenmeyen bir hata oluştu.', 'common.atelierAlt': 'MERS Tassel atölyesi', 'common.jewelryAlt': 'El yapımı takı detayı', 'common.studioDetailAlt': 'MERS Tassel atölyesinden detaylar',
  'footer.tagline': 'Türkiye’de elde şekillenen, yıllarca size eşlik etmesi için tasarlanan küçük güzellikler.', 'footer.explore': 'Keşfet', 'footer.shopAll': 'Tümünü gör', 'footer.new': 'Yeni gelenler', 'footer.atelier': 'Atölyemiz', 'footer.care': 'Müşteri desteği', 'footer.contact': 'İletişim', 'footer.shipping': 'Teslimat ve kargo', 'footer.returns': 'İade ve cayma hakkı', 'footer.jewelryCare': 'Takı bakımı', 'footer.privacy': 'Gizlilik ve güvenlik', 'footer.security': 'Gizlilik ve güvenlik', 'footer.invest': 'MERS’e yatırım', 'footer.notes': 'Atölye notları', 'footer.notesCopy': 'Yeni parçalar ve sakin hikâyeler, ayda bir veya iki kez.', 'footer.email': 'E-posta adresi', 'footer.subscribe': 'Abone ol', 'footer.follow': 'Takip edin ve ulaşın',
  'home.eyebrow': 'İstanbul · 2018’den beri', 'home.title1': 'Biraz', 'home.title2': 'mucize taşıyın.', 'home.lede': 'İstanbul atölyemizde elde tamamlanan, ışığı topladığı kadar hikâye de biriktirmesi için tasarlanan takılar.', 'home.makers': 'Ustalarla tanışın', 'home.proof': '2.400’den fazla koleksiyoner seviyor', 'home.pick': 'Atölyenin seçimi', 'home.handknotted': 'Atölyede elde tamamlandı', 'home.viewProduct': 'Bu parçayı incele', 'home.scroll': 'Keşfetmek için kaydırın',
  'home.handmade': 'Elde üretildi', 'home.handmadeSub': 'İstanbul atölyemizde', 'home.materials': 'Özenle seçilen malzemeler', 'home.materialsSub': 'Güzellik ve dayanıklılık için', 'home.gift': 'Her zaman hediyeye hazır', 'home.giftSub': 'El yazısı notla paketlenir',
  'home.signature': 'İmza seçkisi', 'home.keepClose': 'Hep yakınınızda olsun.', 'home.shopAll': 'Tüm parçaları gör', 'home.ritual': 'Ritüelinizi bulun', 'home.everyday1': 'Her gün için,', 'home.everyday2': 've unutmadığınız günler için.', 'home.pieces': '{{count}} parça',
  'home.hands': 'Önce eller', 'home.slowTitle': 'Anlamlı hiçbir şey aceleyle yapılmaz.', 'home.slowCopy': 'Her MERS parçası eskizden taş seçimine, düğümden cilaya ve son sessiz kontrole kadar küçük ekibimizin ellerinden geçer.', 'home.quote': '“Her nesneyi, sanki şimdiden birinin hatırasıymış gibi üretiyoruz.”', 'home.quoteBy': '— Meral S., kurucu ve usta', 'home.stepInside': 'Atölyeye adım atın', 'home.atelierCaption': 'Atölye · Karaköy, İstanbul',
  'home.review': 'Gerçekte daha da güzel. Ağırlığından küçük ayrıntılarına, kutusuna kadar ilk dokunuştan itibaren özenli hissettiriyor.', 'home.verified': 'Doğrulanmış koleksiyoner · İstanbul', 'home.letters': 'Atölyeden mektuplar', 'home.inbox': 'Daha sakin bir gelen kutusu.', 'home.inboxCopy': 'Yeni nesneler, stüdyo notları ve İstanbul’dan ayrıntılar. Seyrek gönderilir.', 'home.join': 'Listeye katıl', 'home.privacy': 'Abone olarak gizlilik koşullarımızı kabul edersiniz.',
  'catalog.eyebrow': 'Koleksiyon', 'catalog.title1': 'Gündelik', 'catalog.title2': 'mucizeler için.', 'catalog.lede': 'İstanbul’da yavaşça üretildi. Tam anlamıyla sizin hissettirmesi için tasarlandı.', 'catalog.categories': 'Ürün kategorileri', 'catalog.all': 'Tüm parçalar', 'catalog.filters': 'Filtreler', 'catalog.sort': 'Ürünleri sırala', 'catalog.featured': 'Öne çıkanlar', 'catalog.newest': 'En yeniler', 'catalog.low': 'Fiyat: düşükten yükseğe', 'catalog.high': 'Fiyat: yüksekten düşüğe', 'catalog.search': 'Koleksiyonda ara', 'catalog.searchPlaceholder': '“İnci” veya “yüzük” deneyin', 'catalog.clearSearch': 'Aramayı temizle', 'catalog.availability': 'Stok durumu', 'catalog.allAvailability': 'Tüm stok durumları', 'catalog.ready': 'Gönderime hazır', 'catalog.made': 'Sipariş üzerine', 'catalog.material': 'Malzeme', 'catalog.allMaterials': 'Tüm malzemeler', 'catalog.gold': 'Altın vermeil', 'catalog.silver': '925 ayar gümüş', 'catalog.silk': 'İpek', 'catalog.count': '{{count}} özenli parça', 'catalog.clear': 'Filtreleri temizle', 'catalog.empty': 'Parça bulunamadı.', 'catalog.emptyCopy': 'Daha genel bir arama deneyin veya filtreleri temizleyin.', 'catalog.viewAll': 'Tüm parçaları gör', 'catalog.promise': 'MERS sözü', 'catalog.promiseTitle': 'Küçük seriler hâlinde üretilir. Asla seri üretim değildir.', 'catalog.promiseCopy': 'Temponuzu ellerimiz belirler. Bir parça tükendiğinde geri dönmesi biraz zaman alabilir; bazen güzelliğinin bir kısmı da budur.',
  'product.new': 'Yeni', 'product.save': '${{amount}} kazanın', 'product.soldOut': 'Tükendi', 'product.savePiece': '{{name}} parçasını kaydet', 'product.quickAdd': 'Hızlı ekle', 'product.unavailable': 'Stokta yok', 'product.view': '{{name}} parçasını incele',
  'cart.eyebrow': 'Seçiminiz', 'cart.title': 'Alışveriş çantası', 'cart.close': 'Kapat', 'cart.emptyTitle': 'Çantanız zarifçe boş.', 'cart.emptyCopy': 'Yavaşça, elde üretilmiş bir parça keşfedin.', 'cart.remove': '{{name}} parçasını kaldır', 'cart.quantity': '{{name}} adedi', 'cart.decrease': 'Adedi azalt', 'cart.increase': 'Adedi artır', 'cart.subtotal': 'Ara toplam', 'cart.delivery': 'Tahmini teslimat', 'cart.tax': 'Tahmini vergi', 'cart.total': 'Tahmini toplam', 'cart.taxNote': 'Vergi tahminidir ve güvenli ödeme sırasında kesinleşir.', 'cart.complimentary': 'Ücretsiz', 'cart.checkout': 'Ödemeye devam et', 'cart.updateFailed': 'Çanta güncellenemedi', 'cart.addFailed': 'Bu parça alışveriş çantanıza eklenemedi.', 'cart.removeFailed': 'Bu parça çantanızdan kaldırılamadı.', 'cart.quantityFailed': 'Ürün adedi güncellenemedi.',
  'pdp.collection': 'Koleksiyon', 'pdp.handmade': 'Elde üretildi', 'pdp.stories': '{{count}} hikâye', 'pdp.saveAmount': '${{amount}} tasarruf', 'pdp.finish': 'Renk', 'pdp.choose': '{{option}} seç', 'pdp.add': 'Çantaya ekle · ${{amount}}', 'pdp.waitlist': 'Bekleme listesine katıl', 'pdp.stock': 'Atölyede yalnızca {{count}} adet kaldı', 'pdp.delivery': 'Ücretsiz teslimat', 'pdp.deliverySub': 'Eskişehir’e teslim 500 TL+ siparişlerde', 'pdp.returns': 'Kanuni cayma hakkı', 'pdp.returnsSub': '14 gün içinde', 'pdp.care': 'Atölye bakımı', 'pdp.careSub': 'Onarım için bize danışın', 'pdp.story': 'Hikâye ve ayrıntılar', 'pdp.materials': 'Malzeme ve ölçüler', 'pdp.careGuide': 'Bakım rehberi', 'pdp.variation': 'Her parça elde tamamlandığı için küçük farklılıklar karakterinin bir parçasıdır.', 'pdp.careCopy': 'Kuru tutun ve parfümden uzak saklayın. Verilen yumuşak bezle nazikçe silin, kullanımlar arasında kesesinde saklayın.', 'pdp.exploreDetail': 'Ayrıntıları görmek için üzerine gelin', 'pdp.related': 'Keşfetmeye devam edin', 'pdp.love': 'Bunları da sevebilirsiniz.',
  'checkout.secure': 'Güvenli Stripe ödemesi', 'checkout.back': 'Alışverişe devam et', 'checkout.eyebrow': 'Neredeyse sizin', 'checkout.title': 'Ödeme', 'checkout.contact': 'İletişim', 'checkout.contactCopy': 'Makbuzunuz ve teslimat bildirimleri buraya gelecek.', 'checkout.email': 'E-posta adresi', 'checkout.emailError': 'Geçerli bir e-posta adresi girin', 'checkout.delivery': 'Teslimat', 'checkout.deliveryCopy': 'Hızınızı seçin. Teslimat adresinizi bir sonraki adımda Stripe güvenle alır.', 'checkout.standard': 'PTT standart', 'checkout.standardTime': '3–5 iş günü', 'checkout.express': 'Hızlı', 'checkout.expressTime': '1–2 iş günü', 'checkout.payment': 'Güvenli ödeme', 'checkout.paymentCopy': 'Ödemeyi Stripe’ın şifreli ve PCI uyumlu sayfasında tamamlayacaksınız.', 'checkout.methods': 'Kartlar ve yerel ödeme yöntemleri', 'checkout.methodsCopy': 'Kullanılabilir yöntemler bölgenize ve cihazınıza göre uyarlanır.', 'checkout.neverStores': 'MERS Tassel kart numaranızı hiçbir zaman görmez veya saklamaz.', 'checkout.opening': 'Güvenli ödeme açılıyor…', 'checkout.continue': 'Ödemeye devam et · ${{amount}}', 'checkout.legal': 'Stripe açılmadan önce fiyatlar ve stok durumu atölye sunucusu tarafından doğrulanır. Geçerli vergiler güvenli ödeme sayfasında kesinleşir.', 'checkout.summary': 'Sipariş özeti', 'checkout.empty': 'Çantanız boş.', 'checkout.browse': 'Koleksiyona göz atın', 'checkout.trust': 'Güvenli ödeme · 14 gün cayma hakkı · PTT teslimat', 'checkout.emptyToast': 'Çantanız boş', 'checkout.emptyToastCopy': 'Ödemeye geçmeden önce bir parça seçin.', 'checkout.failed': 'Ödeme başlatılamadı', 'checkout.retry': 'Lütfen biraz sonra tekrar deneyin.', 'checkout.orderPlaced': 'Siparişiniz ayrıldı', 'checkout.paymentsUnavailable': 'Bu kurulumda çevrimiçi ödeme etkin değil. Siparişiniz ve stok ayrıldı — ödemeyi tamamlamak için atölye sizinle iletişime geçecek.',
  'success.reference': 'Güvenli onay', 'success.confirming': 'Parçanız doğrulanıyor…', 'success.confirmingCopy': 'Stripe sizi güvenle geri getirdi. İmzalı ödeme onayını bekliyoruz; bu genellikle yalnızca birkaç saniye sürer.', 'success.paid': 'Artık sizin.', 'success.paidCopy': 'Teşekkürler. Parçanız atölyede hazırlanmaya başladı; makbuzunuz e-posta adresinize gönderiliyor.', 'success.failed': 'Ödemeyi yeniden denemeniz gerekiyor.', 'success.failedCopy': 'Herhangi bir ödeme alınmadı. Yeniden denemek istediğinizde çantanız hazır olacak.', 'success.started': 'Atölye hazırlığı başladı', 'success.payment': 'Ödeme durumu: {{status}}', 'success.pieces': '{{count}} parça', 'success.piece': '{{count}} parça', 'success.tryAgain': 'Ödemeyi tekrar dene', 'success.missing': 'Bu onay bağlantısında güvenli oturum bilgisi eksik.', 'success.retrieve': 'Bu sipariş henüz alınamadı.',
  'cancel.eyebrow': 'Ödemeye ara verildi', 'cancel.title': 'Çantanız hâlâ burada.', 'cancel.copy': 'Ödeme tamamlanmadı ve kalıcı çantanızdan hiçbir şey çıkarılmadı. Hazır olduğunuzda ödeme adımına dönebilirsiniz.', 'cancel.return': 'Güvenli ödemeye dön', 'cancel.explore': 'Keşfetmeye devam et',
  'about.eyebrow': 'İstanbul · 2018’den beri', 'about.title1': 'Yavaşça üretildi.', 'about.title2': 'Yıllarca saklandı.', 'about.lede': 'MERS; ipek bir püskül, paylaşılan bir çalışma tezgâhı ve gündelik nesnelerin sıra dışı duygular taşıyabileceği inancıyla başladı.', 'about.beginning': 'Başlangıcımız', 'about.idea': 'Elde bağlanan küçük bir fikir.', 'about.p1': 'Kurucu Meral, İstanbul’un kumaş tüccarları, metal ustaları ve yoğun renkleri arasında büyüdü. Moda dünyasında geçen yılların ardından hatırladığı hareketlere döndü: ipeği düğümlemek, metali cilalamak ve her taşı gözüyle seçmek.', 'about.p2': 'Bir mutfak masasında başlayan yolculuk bugün yakın bir atölye ekibine dönüştü. Hâlâ küçük seriler üretiyor, her parçaya kimin dokunduğunu biliyor ve her siparişi dostlar arasında verilen bir hediye gibi paketliyoruz.', 'about.quote': 'Onu yapan insanı hissedebildiğinizde güzellik başka gelir.', 'about.guides': 'Bize yön verenler', 'about.care': 'Her katmanda özen.', 'about.hands': 'Önce eller', 'about.handsCopy': 'İnsanın ritmi her parçaya ince ve benzersiz bir karakter verir.', 'about.memory': 'Hatıra taşıyan malzemeler', 'about.memoryCopy': 'Güzel yaşlanan ve onarılmaya değer malzemeler seçiyoruz.', 'about.less': 'Daha az, daha iyi', 'about.lessCopy': 'Küçük seriler, düşünülmüş ambalajlar ve geçici trendlerin dışında.', 'about.keepsake': 'Sıradaki hatıranız', 'about.find': 'Size ait hissettiren parçayı bulun.',
  'contact.eyebrow': 'Aramızda bir not', 'contact.title1': 'Sizden haber', 'contact.title2': 'almayı çok isteriz.', 'contact.lede': 'Bir parça, sipariş veya onarım hakkında sorunuz mu var? Küçük destek ekibimiz bir atölye günü içinde yanıt verir.', 'contact.write': 'Yazın', 'contact.visit': 'Ziyaret', 'contact.appointment': 'Randevu ile', 'contact.connect': 'Bağlantıda kalın', 'contact.connectCopy': 'Bize doğrudan yazın veya atölyeyi takip edin.', 'contact.quote': '“Özenli bir yanıt da işçiliğin parçasıdır.”', 'contact.sent': 'Notunuz bize ulaştı.', 'contact.sentCopy': 'Bir atölye günü içinde size döneceğiz.', 'contact.another': 'Başka bir not gönder', 'contact.name': 'Ad soyad', 'contact.email': 'E-posta', 'contact.help': 'Size nasıl yardımcı olabiliriz?', 'contact.product': 'Ürün hakkında soru', 'contact.order': 'Siparişim', 'contact.repairs': 'Onarım ve bakım', 'contact.press': 'Basın ve iş birlikleri', 'contact.message': 'Mesajınız', 'contact.placeholder': 'Biraz daha ayrıntı paylaşın…', 'contact.send': 'Notunuzu gönderin',
  'social.instagram': 'Instagram', 'social.tiktok': 'TikTok', 'social.email': 'E-posta', 'social.whatsapp': 'WhatsApp',
  'auth.welcome': 'Tekrar hoş geldiniz', 'auth.await1': 'Koleksiyonunuz', 'auth.await2': 'sizi bekliyor.', 'auth.loginCopy': 'Siparişlerinizi, kaydettiğiniz parçaları ve atölye bakımını görmek için giriş yapın.', 'auth.password': 'Şifre', 'auth.showPassword': 'Şifreyi göster', 'auth.remember': 'Beni hatırla', 'auth.forgot': 'Şifrenizi mi unuttunuz?', 'auth.signIn': 'Giriş yap', 'auth.signingIn': 'Giriş yapılıyor…', 'auth.new': 'MERS’te yeni misiniz?', 'auth.create': 'Hesap oluşturun', 'auth.loginQuote': 'Sizinle kalması için üretilen sessiz güzellikte nesneler.', 'auth.join': 'Atölyeye katılın', 'auth.begin1': 'Koleksiyonunuza', 'auth.begin2': 'başlayın.', 'auth.signupCopy': 'Favorilerinizi kaydedin, siparişlerinizi izleyin ve özel atölye notları alın.', 'auth.first': 'Ad', 'auth.last': 'Soyad', 'auth.consent': 'Ara sıra atölye notları ve koleksiyonlara erken erişim gönderin.', 'auth.createAccount': 'Hesap oluştur', 'auth.creating': 'Hesap oluşturuluyor…', 'auth.already': 'Zaten koleksiyoner misiniz?', 'auth.signupQuote': 'Hikâyesi olan parçalar için bir yer.', 'auth.loginError': 'Giriş yapılamadı. E-posta adresinizi ve şifrenizi kontrol edin.', 'auth.locked': 'Çok fazla deneme yapıldı. Lütfen birkaç dakika sonra tekrar deneyin.', 'auth.signupError': 'Hesabınız oluşturulamadı. Bilgilerinizi kontrol edin.', 'auth.connectionError': 'Hesap servisi çevrimdışı. Siteyi npm run dev ile yeniden başlatıp tekrar deneyin.', 'auth.emailExists': 'Bu e-posta için zaten bir hesap var. Giriş yapmayı deneyin.', 'auth.passwordRejected': 'En az sekiz karakter, bir harf ve bir rakam içeren bir şifre seçin.', 'auth.firstError': 'Adınızı girin.', 'auth.lastError': 'Soyadınızı girin.', 'auth.emailError': 'Geçerli bir e-posta adresi girin.', 'auth.bagRequired': 'Alışveriş çantanızı kullanmak için giriş yapın veya hesap oluşturun.', 'auth.signOut': 'Çıkış yap',
  'account.eyebrow': 'MERS hesabınız', 'account.greeting': 'Hoş geldiniz, {{name}}.', 'account.lede': 'Koleksiyonunuz, siparişleriniz ve atölye ilişkiniz tek bir özenli yerde.', 'account.memberSince': 'Koleksiyonerlik başlangıcı', 'account.membership': 'Üyelik', 'account.collector': 'MERS koleksiyoneri', 'account.bagEyebrow': 'Tüm cihazlarda kayıtlı', 'account.bag': 'Alışveriş çantanız', 'account.viewBag': 'Çantayı görüntüle', 'account.quantity': 'Adet {{count}}', 'account.bagSummary': 'Çantanızda {{count}} parça', 'account.emptyBag': 'Alışveriş çantanız ilk parçasını bekliyor.', 'account.ordersEyebrow': 'Sipariş geçmişi', 'account.orders': 'Siparişleriniz', 'account.loadingOrders': 'Siparişleriniz getiriliyor…', 'account.ordersError': 'Siparişleriniz şu anda yüklenemedi.', 'account.noOrders': 'Henüz siparişiniz yok. İlk hatıranız hâlâ keşfedilmeyi bekliyor.', 'account.startShopping': 'Koleksiyonu keşfet', 'account.items': '{{count}} ürün', 'account.status.pending': 'Bekliyor', 'account.status.processing': 'Hazırlanıyor', 'account.status.shipped': 'Gönderildi', 'account.status.delivered': 'Teslim edildi', 'account.status.cancelled': 'İptal edildi', 'account.status.refunded': 'İade edildi', 'account.openAtelier': 'Atölye çalışma alanını aç',
};

const messages = { en, tr };

type I18nValue = { locale: Locale; setLocale: (locale: Locale) => void; t: (key: TranslationKey, values?: Record<string, string | number>) => string };
const I18nContext = createContext<I18nValue | null>(null);

export function I18nProvider({ children, initialLocale = 'en' }: { children: ReactNode; initialLocale?: Locale }) {
  const [locale, setLocaleState] = useState<Locale>(initialLocale);
  useEffect(() => {
    const saved = window.localStorage.getItem('mers-locale');
    if (saved === 'tr' || saved === 'en') setLocaleState(saved);
  }, []);
  const setLocale = useCallback((next: Locale) => {
    setLocaleState(next);
    window.localStorage.setItem('mers-locale', next);
    document.cookie = `mers-locale=${next};path=/;max-age=31536000;samesite=lax`;
  }, []);
  useEffect(() => { document.documentElement.lang = locale; }, [locale]);
  const t = useCallback((key: TranslationKey, values?: Record<string, string | number>) => translate(locale, key, values), [locale]);
  const value = useMemo(() => ({ locale, setLocale, t }), [locale, setLocale, t]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function translate(locale: Locale, key: TranslationKey, values?: Record<string, string | number>) {
  let text: string = messages[locale][key];
  for (const [name, value] of Object.entries(values || {})) text = text.replaceAll(`{{${name}}}`, String(value));
  return text;
}

export function useI18n() {
  const value = useContext(I18nContext);
  if (!value) throw new Error('useI18n must be used within I18nProvider');
  return value;
}
