'use client';

import { Check, Clock3, MoreHorizontal, Plus, Search, ShieldCheck, UserPlus, X } from 'lucide-react';
import { useState } from 'react';

const staff=[{name:'Derya Selin',email:'derya@merstattel.com',role:'Owner',initials:'DS',last:'Active now'},{name:'Meral Aydın',email:'meral@merstattel.com',role:'Catalog manager',initials:'MA',last:'12 min ago'},{name:'Ece Polat',email:'ece@merstattel.com',role:'Customer care',initials:'EP',last:'38 min ago'},{name:'Jon Bell',email:'jon@merstattel.com',role:'Marketing analyst',initials:'JB',last:'Yesterday'}];
const permissions=['View','Create','Edit','Delete','Export']; const resources=['Orders','Products','Inventory','Customers','Marketing','Support','Team'];
export default function UsersPage(){const [invite,setInvite]=useState(false);const [role,setRole]=useState('Catalog manager');return <><div className="admin-page-heading"><div><span className="admin-kicker">Access control</span><h1>People & roles</h1><p>Give every team member exactly the access they need.</p></div><button className="admin-button admin-button--primary" onClick={()=>setInvite(true)}><UserPlus size={15}/> Invite team member</button></div>
<section className="people-layout"><article className="admin-card team-card"><header className="card-heading"><div><span>Workspace members</span><h2>Team</h2></div><label className="compact-search"><Search/><input placeholder="Search team"/></label></header>{staff.map((person)=><div className="team-row" key={person.email}><span>{person.initials}</span><div><strong>{person.name}</strong><small>{person.email}</small></div><b>{person.role}</b><time><Clock3/>{person.last}</time><button className="table-more"><MoreHorizontal/></button></div>)}</article><aside className="admin-card role-list"><header><span>Roles</span><button><Plus/></button></header>{['Owner','Catalog manager','Customer care','Marketing analyst','Fulfillment'].map((item,index)=><button key={item} className={role===item?'active':''} onClick={()=>setRole(item)}><span><ShieldCheck/></span><div><strong>{item}</strong><small>{index===0?'Full access':`${8-index} permissions`}</small></div><b>{index===0?1:index===1?2:1}</b></button>)}</aside></section>
<section className="admin-card permission-card"><header className="card-heading"><div><span>Permission matrix</span><h2>{role}</h2></div><p>Changes apply immediately to 2 team members.</p></header><div className="permission-table"><div className="permission-row permission-head"><span>Resource</span>{permissions.map((permission)=><span key={permission}>{permission}</span>)}</div>{resources.map((resource,row)=><div className="permission-row" key={resource}><strong>{resource}</strong>{permissions.map((permission,col)=><label key={permission}><input type="checkbox" defaultChecked={role==='Owner'||((row+col)%3!==0&&col<3)}/><i><Check/></i></label>)}</div>)}</div><footer><button className="admin-button admin-button--secondary">Discard changes</button><button className="admin-button admin-button--primary">Save permissions</button></footer></section>
{invite&&<div className="modal-root"><button className="modal-scrim" onClick={()=>setInvite(false)} aria-label="Close"/><div className="invite-modal glass-overlay"><header><div><span className="admin-kicker">Workspace access</span><h2>Invite someone</h2></div><button className="icon-button" onClick={()=>setInvite(false)}><X/></button></header><p>They’ll receive an email with a secure link to join MERS Atelier.</p><label>Email address<input type="email" placeholder="name@merstattel.com"/></label><label>Role<select><option>Customer care</option><option>Catalog manager</option><option>Marketing analyst</option><option>Fulfillment</option></select></label><div><button className="admin-button admin-button--secondary" onClick={()=>setInvite(false)}>Cancel</button><button className="admin-button admin-button--primary" onClick={()=>setInvite(false)}>Send invitation</button></div></div></div>}</>}
