'use client';

import { useMemo, useState } from 'react';
import { Check, ChevronDown, Download, Filter, MoreHorizontal, Search, X } from 'lucide-react';
import { orders } from '@/data/store';

export default function OrdersPage() {
  const [query,setQuery] = useState(''); const [status,setStatus] = useState('All'); const [selected,setSelected] = useState<string[]>([]);
  const visible = useMemo(() => orders.filter((order) => (status==='All'||order.status===status) && `${order.id} ${order.customer} ${order.email}`.toLowerCase().includes(query.toLowerCase())),[query,status]);
  const toggleAll = () => setSelected(selected.length===visible.length ? [] : visible.map((order)=>order.id));
  return <><div className="admin-page-heading"><div><span className="admin-kicker">Operations</span><h1>Orders</h1><p>Track, fulfill and care for every order in one place.</p></div><div><button className="admin-button admin-button--secondary"><Download size={15}/> Export</button><button className="admin-button admin-button--primary">Create order</button></div></div>
    <div className="admin-card table-card"><div className="table-toolbar"><label className="table-search"><Search size={16}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search order, customer or email"/>{query&&<button onClick={()=>setQuery('')}><X size={14}/></button>}</label><div className="status-tabs">{['All','Processing','Shipped','Delivered','Cancelled'].map((item)=><button key={item} onClick={()=>setStatus(item)} className={status===item?'active':''}>{item}{item==='All'&&<span>{orders.length}</span>}</button>)}</div><button className="filter-pill"><Filter size={14}/> More filters <ChevronDown size={14}/></button></div>
    {selected.length>0&&<div className="batch-bar"><span><Check size={14}/> {selected.length} selected</span><button>Mark fulfilled</button><button>Print slips</button><button>Archive</button><button onClick={()=>setSelected([])}>Clear</button></div>}
    <div className="admin-table admin-table--large"><table><thead><tr><th><input type="checkbox" checked={visible.length>0&&selected.length===visible.length} onChange={toggleAll} aria-label="Select all orders"/></th><th>Order</th><th>Date</th><th>Customer</th><th>Channel</th><th>Status</th><th>Items</th><th>Total</th><th></th></tr></thead><tbody>{visible.map((order)=><tr key={order.id}><td><input type="checkbox" checked={selected.includes(order.id)} onChange={()=>setSelected((current)=>current.includes(order.id)?current.filter((id)=>id!==order.id):[...current,order.id])} aria-label={`Select ${order.id}`}/></td><td><strong>{order.id}</strong></td><td>{order.date}</td><td><div className="customer-cell"><span>{order.customer.split(' ').map((n)=>n[0]).join('')}</span><section><strong>{order.customer}</strong><small>{order.email}</small></section></div></td><td>{order.channel}</td><td><span className={`status status--${order.status.toLowerCase()}`}>{order.status}</span></td><td>{order.items}</td><td><strong>${order.total}</strong></td><td><button className="table-more"><MoreHorizontal size={17}/></button></td></tr>)}</tbody></table></div>
    <div className="table-footer"><span>Showing {visible.length} of {orders.length} orders</span><div><button disabled>Previous</button><button className="active">1</button><button>2</button><button>Next</button></div></div></div></>;
}
